export const gymData = [
  {
    id: '1',
    name: 'Underground Fitness',
    address: '2217 San Ramon Valley Blvd Suite E, San Ramon, CA',
    equipment: ['Dumbbells', 'T bar', 'Kettle Bells', 'Landmine Press', 'Pull up bar', 'Benches', 'Bumper Plates'],
    hours: 'Mon-Fri: 6am-10pm, Sat-Sun: 8am-8pm',
    description: 'A premier powerlifting gym with state-of-the-art equipment.',
    latitude: 37.7812607,
    longitude: -121.9789704,
  },
  {
    id: '2',
    name: '24 Hour Fitness',
    address: '4770 Willow Rd, Pleasanton, CA',
    equipment: ['Barbells', 'Squat Racks', 'Benches', 'Adjustable Benches', 'Dumbbells', 'Cardio Equipment'],
    hours: 'Mon-Sun: 24 hours',
    description: 'Pleasanton 24 Hour Fitness',
    latitude: 37.6979806,
    longitude: -121.8989944,
  },
  {
    id: '3',
    name: '24 Hour Fitness',
    address: '4450 Norris Canyon Rd, San Ramon, CA',
    equipment: ['Barbells', 'Squat Racks', 'Benches', 'Adjustable Benches', 'Dumbbells', 'Cardio Equipment'],
    hours: 'Mon-Sun: 24 hours',
    description: 'San Ramon 24.',
    latitude: 37.7740072,
    longitude: -121.9721244,
  },
  {
    id: '4',
    name: 'California Strength',
    address: '1538, 2021 Omega Rd #120, San Ramon, CA',
    equipment: ['Bumper Plates', 'Wood Jerk Blocks', 'Power Bars', 'Squat Racks', 'Dumbbells'],
    hours: 'Mon-Sun: hours',
    description: 'CrossFit and Powerlifting gym offering classes for all ages.',
    latitude: 37.783751,
    longitude: -121.982413,
  },
  {
    id: '5',
    name: 'Reform Fitness',
    address: '1279 Quarry Ln, Pleasanton, CA',
    equipment: ['Dumbbells'],
    hours: 'Mon-Sun: hours',
    description: '',
    latitude: 37.6756827,
    longitude: -121.8651654,
  },
  {
    id: '6',
    name: 'Bay Area Barbell',
    address: '2824 Regatta Blvd, Richmond, CA',
    equipment: [
      '6 Combo Racks (5 TSS & 1 ER)',
      '4 Deadlift Platforms',
      '2 Olympic Weightlifting Platforms',
      '2 Power Cages',
      '7,000+ lbs of Rogue Powerlifting Calibrated Plates',
      '2 full sets of Rogue Olympic Bumper Plates',
      '2 Eleiko Power Bars',
      'Kabuki Deadlift Bar',
      '10 Rogue Ohio Power Bars',
      '5 lbs - 120 lbs Dumbbells',
      'Leg Press Machine',
      'Lat Pull Down/ Low Row Machine'
    ],
    hours: 'Members: 5 AM - 11 PM last entry',
    description: 'The East Bay’s Premier Powerlifting Gym. USAPL-friendly.',
    latitude: 37.9146829,
    longitude: -122.3416504,
  },
  {
    id: '7',
    name: 'Backyard Barbell',
    address: '1630 Remuda Ln, San Jose, CA 95112',
    equipment: [
      'Competition Combo rack',
      'Power racks',
      'Kabuki Powerlifting plates',
      'Eleiko competition plates',
      'Strong man equipment: Yoke, Log, Farmer handles, Sled, Husafell stone, wheel barrow, Hungarian core blaster',
      'Texas Squat, Deadlift, and Power bars',
      'Safety squat bar, Duffalo bar, Swiss bar and every kind of specialty bar you can think of',
      'Belt squat Machine',
      'Elitefts Monster hack squat',
      'Reverse Hyper',
      'Dip bars',
      'Chest supported Row',
      'Bands, chains, and weight releasers',
      'Flat and adjustable benches',
      'Blocks for Block pulls and deficit deadlifts',
      'Deadlift platform with band attachments',
      'Dumbells 5-150lbs',
      '250lbs stack Lat pulldown with various attachments such as Fat Gripz, grenade handles, Different lat pulldown handles',
      'And much much more!'
    ],
    hours: 'Open 24 Hours, 365 days a year',
    description: 'USAPL-friendly.',
    latitude: 37.37279,
    longitude: -121.9087,
  },
  {
    id: '8',
    name: 'War Cat Fitness',
    address: '299 Bassett St, San Jose, CA',
    equipment: [
      '5 Texas Strength Systems Powerlifting Competition Racks (with updated Bench Pads)',
      'Rogue Powerlifting Competition Plates 1.25, 2.5, 5, 10, 15, 20, 25, 50kg Plates',
      'Cast Iron 2.5, 5, 10, 25 and 45lb Plates',
      '20kg Ohio Power Barbells',
      '45lb Ohio Power Barbells',
      '20kg Texas Strength Systems Barbell',
      '45lb Texas Deadlift Barbells',
      '45lb Rogue Deadlift Barbells',
      '45lb Kansas Power Barbells',
      '5 Deadlift Platforms',
      'Dumbbells 2.5-100lbs',
      'Kettlebells 10-175lbs',
      'Plate Loaded Dumbbells',
      '4 Elite Pro Adjustable Benches',
      '2 Rogue Flat Benches',
      '2 Rogue Westside Benches',
      '4 Power Rack Stations',
      'Landmine Row Station',
      'Rogue Iso Leg Press Machine',
      'Rogue Belt Squat Machine',
      'Rogue Reverse Hyper',
      'Rogue Lat Pulldown / Row Machine',
      'Double Column Cable Machine',
      'GHD Machine',
      '10’x10’ Stretching / Grappling Mat',
      '2 Assault AirBikes (for warming up)'
    ],
    hours: 'Monday - Friday: 5AM - 10PM, Saturday: 8 AM - 4 PM, Sunday: 8 AM - 2 PM',
    description: 'Best Strength Gym in The Bay Area. USAPL-friendly.',
    latitude: 37.3391466,
    longitude: -121.9004172,
  },
  {
    id: '9',
    name: '1RM Strength',
    address: '23412 Lyons Ave, Santa Clarita, CA',
    equipment: [
      'Texas Strength Systems Combo x2',
      'Ghost Combo Rack x2',
      'Rogue Combo Rack x1',
      'Deadlift Platforms x3',
      'Prime Fitness Leg Extension x1',
      'Prime Fitness Seated Row x1',
      'Prime Fitness Leg Press x1',
      'Prime Fitness Plate Loaded Incline Chest Press x1',
      'Atlantis Strength Lying Leg Curl',
      'Rogue Power Rack x1',
      'Rogue Squat Stand x1',
      'Rogue GHD x1',
      'Rogue Westside Reverse Hyper x1',
      'Rogue Belt Squat x1',
      'Rogue Adjustable Bench x2',
      'Flat Bench x2',
      '5-75lb Dumbbells x1',
      'Functional Trainer (Cables) x1',
      'Lat Pulldown/Low Row Machine x1',
      'Rogue Echo Bike x1',
      'Prime Fitness Attachments',
      'Hammer Strength Adductor/Abductor'
    ],
    hours: 'MWF: 3PM-9PM, TTh: 9AM-9PM, Sat:10AM-3PM, Sun:Closed',
    description: 'Premier Powerlifting & Powerlifting Gym. USAPL-friendly.',
    latitude: 34.3785292,
    longitude: -118.5430867,
  },
  {
    id: '10',
    name: 'Hidden Strength Gym',
    address: '1442 Arrow Hwy K, Irwindale, CA',
    equipment: [
      'Powerlifting',
      '5 Combo Racks',
      '3 Deadlift Platforms',
      'Calibrated Kilo Plates',
      '3 EliteFTS Comp. Benches',
      'Rogue Deadlift Bars & Ohio Power Bars',
      'Specialty bars (Safety Squat Bar, Duffalo Bar)',
      'Olympic lifting',
      'Olympic platform',
      'American Barbell Olympic Bar',
      'Bumper plates',
      'Strength/weight training',
      '6 Station Squat Rig',
      '8 Station Cable Tower',
      '5 - 125 LB Dumbbells',
      'Adjustable Benches (Incline, Decline, Flat)',
      'Leg Extension/Hamstring Curl Station',
      'Glute Hamstring Developer (GHD)',
      'Belt Squat',
      'Specialty Bars (EZ Bar, Trap Bar, Multi grip bar)',
      'Tricep Dip Stand',
      'Reverse Hyper',
      'Kettlebells, Medicine balls, Ply boxes, Battle Ropes'
    ],
    hours: '24/7',
    description: 'The #1 Private Gym in Irwindale. We have the equipment and environment that will help you reach your full potential. Open 24/7, 365 days. USAPL-friendly.',
    latitude: 34.1131857,
    longitude: -117.973448,
  },
  {
    id: '11',
    name: 'Exceed Performance',
    address: '2060 S Euclid St K, Anaheim, CA',
    equipment: [
      '1 Texas Strength System Combo Rack',
      '1 State of the Arc Combo Rack',
      '4 Custom',
      '1 Squat-only rack',
      '1 Power cages',
      '5 Deadlift Platforms',
      '2 Assault Bikes',
      '1 Treadmill',
      'Dumbbell sets 5-120lbs',
      'Dumbbell sets 5-50lbs',
      'Lat pulldown & mid row machine',
      'Leg press & hack squat machine',
      'Leg extension & leg curl plate loaded machine',
      'Glute Ham Developer',
      '2 Adjustable incline benches',
      'Functional Trainer Cable machine',
      '1 Flat Texas bench',
      '3000kg of powerlifting competition plates',
      '2000lbs of iron plates',
      '2000lbs of Uesaka & Neon Weightlifting Bumper Plates',
      '8 Power Bars',
      '2 Texas power bars',
      '4 deadlift bars',
      '2 DUFFALO BARS',
      '2 Safety Squat Bars',
      '3 squat bars',
      '1 OPEN trap bar',
      '1 swiss bar',
      '1 KABUKI POWER BAR',
      '1 KABUKI SQUAT BAR',
      '1 KABUKI DEADLIFT BAR',
      '3 men’s weightlifting bars',
      '2 women’s weightlifting bar',
      '2 Large Plyo Boxes',
      '2 Small Plyo Boxes',
      'Resistance bands from 10lbs-120lbs'
    ],
    hours: 'MONDAY-FRIDAY 10AM-7PM, 24 HOUR ACCESS FOR MEMBERS!',
    description: 'Powerlifting At It’s Finest In Anaheim, California! USAPL-friendly.',
    latitude: 33.7964012,
    longitude: -117.9403234,
  },
  {
    id: '12',
    name: 'Old Skool Iron',
    address: '33 Commerce Pl, Vacaville, CA',
    equipment: [
      'six dead-lift platforms',
      'three ER Combo racks',
      'four power racks (full and half rack)',
      'deadlift bars',
      'squat bars',
      'smith machine',
      'competition Forza bench',
      'full rack of dumbbells up to 160 lbs. (going even heavier in the near future)',
      'adjustable moveable benches etc'
    ],
    hours: 'Mon - Fri 8:00am to 8:00pm Sat/Sun 8:00am to 4:00pm Open 365 days a year',
    description: 'A Serious Place To Lift and Train Hard. USPA-friendly.',
    latitude: 38.3533328,
    longitude: -121.9355117,
  },
  {
    id: '13',
    name: 'Get Bent Training',
    address: '2341 San Pablo Ave, Oakland, CA 94612',
    equipment: [
      'Deadlift Bars',
      'Squat Bars',
      'Calibrated Plates',
      'Squat Racks',
      'Dumbbells',
      'Turf Area',
      'Safety Squat Bar',
      'Treadmills',
      'Kettlebells',
      'More'
    ],
    hours: 'Mon-Sat: 6:00 AM - 8:00 PM, Sun: Closed',
    description: 'Powerlifting gym featuring athletic equipment and inclusive community. Hosts USPA competitions. Perfect for athletes looking to get stronger, and the general individual.',
    latitude: 37.8141832,
    longitude: -122.2748394,
  },
  {
    id: '14',
    name: 'The Resistance Gym',
    address: '3442 Clayton Road, Concord, CA',
    equipment: [
      'Deadlift Bars',
      'Squat Racks',
      'Calibrated Plates',
      'Dumbbells',
      'Turf Area',
      'Monolifts'
    ],
    hours: 'Daily: 5:00 AM - 11:00 PM',
    description: 'An inclusive, accessible space to lift heavy weights! Hosts USPA competitions. Best for powerlifters, strongmen, Olympic lifting, etc.',
    latitude: 37.9711276,
    longitude: -122.0140201,
  },
  {
    id: '15',
    name: 'Central Strength Gym',
    address: '827 W Hamilton Ave, Campbell, CA 95008, USA',
    equipment: [
      'Deadlift Bar',
      'Squat Bar',
      'Squat Racks',
      'Monolifts',
      'Atlas Stones',
      'Axle Bar',
      'General Strongman Equipment',
      'Various Machines'
    ],
    hours: 'Mon-Fri: 9:00 AM - 8:00 PM, Sat: 9:00 AM - 1:00 PM, Sun: Closed',
    description: 'Hosts USPA competitions. Perfect for powerlifters and strongmen.',
    latitude: 37.2949683,
    longitude: -121.9639524,
  },  
  {
    id: '16',
    name: 'Untamed Strength',
    address: '5780 Auburn Blvd, Sacramento, CA 95841',
    equipment: [
      'Yoke',
      'Logs',
      'Calibrated Plates',
      'Bumper Plates',
      'Axle Bars',
      'Sandbags',
      'Atlas Stones',
      'Tyres',
      'Farmers Handles',
      'Odd Implements',
      'Platforms',
      'Monolift',
      'Powerstairs',
      'Car Deadlift',
      'Husafell Stones',
      'Viking Press'
    ],
    hours: 'Varies Based on Membership. Appointment Only.',
    description: '',
    latitude: 38.67107,
    longitude: -121.3294601,
  },
  {
    id: '17',
    name: 'Third Street Barbell',
    address: '2010 3rd St, Sacramento, CA 95818, United States',
    equipment: [
      '6 Full Squat Stations',
      '2 Competition Bench Presses',
      '2 Combo Racks',
      '3 Deadlift Platforms',
      '4 Olympic Platforms',
      'Eleiko and Ivanko Plates (Standard and Bumper)',
      'Full Competition Calibrated Kilo Set',
      '5-lb to 100-lb Dumbbells in 2.5-lb Increments',
      'Powerlifting & Weightlifting Bars from Eleiko, Texas Strength Systems, Rogue, and Kabuki Strength',
      'Rogue Rhino Belt Squat Machine',
      'Full Body Hammer Strength Plate-Loaded Circuit',
      '9 Flat/Incline Benches',
      '2-250lbs Cable Stacks',
      'Onnit Kettlebells',
      'Glute-Ham Developer',
      'Concept 2 Rower',
      'Assault Bike',
      'Step Mill',
      'Full Treadmill',
      'Turf'
    ],
    hours: 'Mon-Fri: 8:00 AM - 8:00 PM, Sat: 8:00 AM - 12:00 PM, Sun: Closed',
    description: 'A friendly, clean, neighborhood barbell gym.',
    latitude: 38.5714617,
    longitude: -121.5079948,
  },
  {
    id: '18',
    name: 'An Iron Movement',
    address: '565 6th St, San Francisco, CA 94107',
    equipment: [
      'Platforms',
      'Barbells (Including Women\'s 15kg Weightlifting Bars, Kids / Technique Bars, Power Bars, etc.)',
      'Bumper Plates',
      'Jerk Blocks',
      'Squat Stands',
      'Calibrated Steel Plates',
      'Racks',
      'Combo Rack',
      'Competition Style Benches'
    ],
    hours: 'Personal Training. Hours May Vary.',
    description: 'Perfect for weightlifting and powerlifting. Offers classes throughout the week for each.',
    latitude: 37.7753649,
    longitude: -122.4014457,
  },
  {
    id: '19',
    name: 'Iron Warehouse',
    address: '1203 San Luis Obispo Ave, Hayward, CA 94544, USA',
    equipment: [
      'Calibrated Steel Plates',
      'Bumper Plates',
      'Competition Benches',
      'Racks',
      'Deadlift Platforms',
      'Weightlifting Platforms',
      'Squat Stands',
      'Weightlifting Bars',
      'Powerlifting Bars',
      'Yoke',
      'Sled',
      'Loadable Circus Dumbbell'
    ],
    hours: 'Hours Vary, Classes Offered, See Website for Details.',
    description: 'Gym for powerlifting, Olympic weightlifting, and strongman. Hosts USAPL meets, as well as offers lifting parties.',
    latitude: 37.6080997,
    longitude: -122.0517811,
  },
  {
    id: '20',
    name: 'Warcat Strength Gym',
    address: '1033 S Bascom Ave, San Jose, CA 95128, United States',
    equipment: [
      '4 Combo Racks',
      '6 Squat Racks',
      '5 Power Rack Cages',
      '4 Upright racks (outdoor)',
      '2 Westside Rogue Bench Press Stations',
      '5 Deadlift Platforms',
      'Belt Squat',
      'All Specialty Bars',
      'Complete Accessory Machines',
      'Calibrated steel competition Plates',
      'Dumbbell Racks from 5-120lbs',
      'Reverse Hyperextension',
      'Belts, Chains, Chalk, Bands',
      'Rogue Yoke',
      'Log Bar (10in & 15 in)',
      'Atlas Stones (92lbs - 300) & Crash Pads',
      'Axle Bar',
      'Heavy Sandbags',
      'Farmers Carry Bars',
      'Sandbags',
      'Tires',
      'Farmer\'s handles',
      'Sled',
      'Olympic Lifting Platform',
      'Rogue Ohio Bar',
      'Rogue Olympic Lifting Bumper Plates',
      'Mono Rack'
    ],
    hours: 'Sunday: 8AM-2PM, Monday-Friday: 5AM-10PM, Saturday: 8AM-4PM',
    description: 'Aims to assemble strong gym and fitness brands from a variety of different training disciplines.',
    latitude: 37.296870,
    longitude: -121.933908,
  },
  {
    id: '21',
    name: 'Santa Cruz Strength',
    address: '151 Harvey West Blvd STE D, Santa Cruz, CA 95060, United States',
    equipment: [
      'calibrated plates',
      'platforms',
      'bumper plates',
      'monolift',
      'combo rack',
      'atlas stones',
      'monster dumbbell',
      'Inch dumbbells',
      'kegs',
      'yoke',
      'log',
      'assault bikes',
      'jerk blocks',
      'racks',
      'chains',
      'bands'
    ],
    hours: 'Sunday: 10AM-2PM, Monday-Friday: 6AM-8PM, Saturday: 8AM-4PM',
    description: 'Perfect for powerlifters and strongmen looking to improve',
    latitude: 36.982010,
    longitude: -122.035265,
  },
  {
    id: '22',
    name: 'The Training Hall',
    address: '996 Lawrence Dr # 101, Thousand Oaks, CA 91320',
    equipment: [
      'Bumper plates',
      'squat racks',
      'chalk',
      'cast iron plates',
      'atlas stones',
      'benches',
      'viking press',
      'sled'
    ],
    hours: 'Strongman Saturdays: 12PM-3PM, Arm Lifting Sundays: 11AM-12PM, Mas Wrestling Sundays: 12PM-1PM',
    description: 'For strongmen. Need to contact for sessions.',
    latitude: 34.1926345,
    longitude: -118.929512,
  },
  {
    id: '23',
    name: 'Gold\’s Gym',
    address: '360 Hampton Dr, Venice, CA 90291',
    equipment: [
      'squat racks',
      'benches',
      'barbells',
      'weights',
      'iron plates',
      'dumbbells',
      'machines'
    ],
    hours: '5AM-11PM everyday',
    description: 'The Mecca of Bodybuilding',
    latitude: 33.9953333,
    longitude: -118.4753611,
  },
  {
    id: '24',
    name: 'Big Speed and Strength',
    address: '8469 Cherry Ave C, Fontana, CA 92335',
    equipment: [
      'Barbells/Dumbbells',
      'Medicine/Wall/Stability Balls',
      'Workout Benches',
      'Preacher Curl',
      'EZ Bars',
      'Squat/Power Racks',
      'Hamstring Curl Machines',
      'Leg Press',
      'Bumper Plates',
      'Steel Plates',
      'Sand Buckets',
      'TRX Cables',
      'Monkey Bars',
      'Power-lifting Bench',
      'Monolift',
      'Cross Cable Machine',
      'GHD Machine',
      'T-Back Row Machine',
      'Peck Deck',
      'Leg Extension',
      'Belted Squat Station',
      'Power Lifting Platforms',
      'Trap Dead-lift Bar',
      'Sandbags',
      'Duffalo Bar',
      'Safety Squat Bar',
      'Strongman Equipment: Logs (large and medium), Stones, Farmers carries, Yoke, Axles, Husafell stone, Keg'
    ],
    hours: 'Weekdays: 7AM-11AM & 3PM-8PM, Weekends: 8AM-10AM',
    description: 'Never be outworked.',
    latitude: 34.100341,
    longitude: -117.4879786,
  },
  {
    id: '25',
    name: 'House Of Power',
    address: '6342 Industry Way Suite B, Westminster, CA 92683',
    equipment: [
      'Over 14,000 lbs of free weights',
      'Several high-quality adjustable power racks with chin-up bars',
      'Olympic lifting platforms with various benches',
      'Wide variety of bands, chains, and weight releasers',
      'Plyo boxes for plyometrics, step-ups, and box squats',
      'Kettlebells, sandbags, steel logs, kegs, wall balls, medicine balls',
      'Dumbbells from 5 lbs to 150 lbs',
      'Cable machines for pull-downs, rowing, and double cable stack',
      'Full line of plate-loaded machines',
      '100\’s feet of wall space for dynamic medicine ball work',
      '1500 sq ft of turf for tire flips, sled drags, farmer walks, yoke walks, or running',
      'Foam rollers, exercise mats, jump ropes, and nylon straps',
      'Assault Fitness Bikes and Cardio Equipment'
    ],
    hours: '24/7 gym. Day passes available 9-5 Mon-Fri, and can be purchased in advance for late-night access.',
    description: 'THE STRONGEST GYM IN OC. We have multiple high-performance programs with decades of results, happy athletes, and clients.',
    latitude: 33.7514682,
    longitude: -118.0187002,
  },
  {
    id: '26',
    name: 'Empire Barbell',
    address: '1200 Arizona St, Redlands, CA 92374',
    equipment: [
      'Squat Racks',
      'Platforms',
      'Logs',
      'Circus Dumbbells',
      'Chains',
      'Bumper plates',
      'Grip training tools'
    ],
    hours: 'Hours may vary',
    description: 'Contact in advance for drop-in.',
    latitude: 34.0683889,
    longitude: -117.20675,
  },
  {
    id: '27',
    name: 'Max\’s Gym',
    address: '2607 Mandela Pkwy, Oakland, CA 94607, United States',
    equipment: [
      'Bumper plates',
      'Power Rack',
      'Squat Rack',
      'Power Bars',
      'Calibrated Plates'
    ],
    hours: 'Sunday Closed, Monday 7 AM-8 PM, Tuesday 7 AM-8 PM, Wednesday 9 AM-8 PM, Thursday 7 AM-8 PM, Friday 7 AM-8 PM, Saturday 9 AM-2:30 PM',
    description: 'Max\’s Gym is based in Oakland, where we train in the sports of powerlifting, weightlifting, and supertotal. We are a family gym with a friendly atmosphere. Offers women\'s class, team training, and weightlifting technique. USAPL-friendly.',
    latitude: 37.8208713,
    longitude: -122.2893771,
  },
  {
    id: '28',
    name: 'Full Grip Barbell',
    address: '1387 Lowrie Ave, South San Francisco, CA 94080',
    equipment: [
      'Bumper plates',
      'Squat racks',
      'Dumbbells',
      'Calibrated plates',
      'Kettlebells'
    ],
    hours: 'Sunday Closed, Monday 6-9 AM, 3:15-8 PM, Tuesday 6-9 AM, 3:15-8 PM, Wednesday 6-9 AM, 3:15-8 PM, Thursday 6-9 AM, 3:15-8 PM, Friday 6-9 AM, 3:15-8 PM, Saturday Closed',
    description: 'Our 2,500 sq. ft. facility is located in South San Francisco off of Highway 101. There\'s plenty of parking in front of the gym and two friendly dogs to meet you at the door. We pride ourselves on providing excellent equipment which includes enough racks for everyone, barbells, bumper and iron plates and olympic weightlifting platforms. Nothing fancy, just the right tools to get you strong. We are a USAPL Friendly gym.',
    latitude: 37.6485901,
    longitude: -122.4108586,
  },
  {
    id: '29',
    name: 'Train Origin',
    address: '405 Old County Road, Belmont, CA 94002',
    equipment: [
      'Bumper plates',
      'Iron plates',
      'Squat rack',
      'Kettlebells'
    ],
    hours: 'May vary',
    description: 'Whether you are working 1 on 1 with a coach, or within the Origin Group Experience, you will be surrounded by a supportive community of peers and coaches. With time and effort, all things are possible. USAPL-friendly.',
    latitude: 37.5265884,
    longitude: -122.2819812,
  },
  {
    id: '30',
    name: 'Boss Barbell Club',
    address: '241 Polaris Ave, Mountain View, CA',
    equipment: [
      'Turf area',
      'Chalk',
      'Calibrated plates',
      'Deadlift bar/platform',
      'Benches',
      'Power bars',
      'Chains',
      'Various equipment',
      'Easy curl bar',
      'Bumper plates',
      'Hamstring machines',
      'Rope climb',
      'T bar row',
      'Belt squat machine',
      'Cambered bar',
      'Sled',
      'Yoga room',
      'Cardio equipment',
      'Mono lift',
      'Resistance bands'
    ],
    hours: 'Monday 6:00 AM - 10:00 PM, Tuesday 6:00 AM - 10:00 PM, Wednesday 6:00 AM - 10:00 PM, Thursday 6:00 AM - 10:00 PM, Friday 6:00 AM - 10:00 PM, Saturday 9:00 AM - 5:00 PM, Sunday 8:00 AM - 8:00 PM',
    description: 'USAPL-friendly. Big gym with equipment to fit every goal.',
    latitude: 37.3986672,
    longitude: -122.0835519,
  },
  {
    id: '31',
    name: 'The Compound LB',
    address: '963 W Pacheco Blvd, Los Banos, CA 93635',
    equipment: [
      'Dumbbells',
      'Trap bar',
      'Deadlift bar',
      'Leg Press machine',
      'Benches',
      'Swiss Bar',
      'Calibrated Plates',
      'Iron Plates',
      'Squat Rack'
    ],
    hours: 'Open 24/7 365 days a year',
    description: 'The Compound Physical Fitness Facility is not geared towards just one type of lifters. We invite everyone to come see what we have and what we can offer. Come check us out for yourself! USAPL-friendly.',
    latitude: 37.0557174,
    longitude: -120.8699645,
  },
  {
    id: '32',
    name: 'Legion Training Camp',
    address: '1570 Tollhouse Rd, Clovis, CA 93611',
    equipment: [
      'T Bar',
      'Cambered bar',
      'Calibrated plates',
      'Cardio equipment',
      'Leg press',
      'Pull up rings',
      'Dumbbells',
      'Deadlift platforms',
      'Bench press platforms',
      'Iron plates',
      'Squat rack',
      'Bumper plates',
      'Power bar'
    ],
    hours: '24/7',
    description: 'IPF certified equipment, Olympic styled platform, Strongman area.',
    latitude: 36.82879,
    longitude: -119.6870336,
  },
  {
    id: '33',
    name: 'Absolute Flex Appeal',
    address: '1106 Tinker Rd #150, Rocklin, CA 95765',
    equipment: [
      'Various machines',
      'Bench press',
      'Power bar',
      'Bumper plates',
      'Turf',
      'Squat racks',
      'Dumbbells',
      'Medicine balls',
      'Kettlebells',
      'Torque Fitness Tank'
    ],
    hours: 'Sunday Closed, Monday 4 AM-11 PM, Tuesday 4 AM-11 PM, Wednesday 4 AM-11 PM, Thursday 4 AM-11 PM, Friday 4 AM-11 PM, Saturday 4 AM-8 PM',
    description: 'Together, through hard work, accountability, and relentless effort, we provide an environment that not only helps trainers start and grow their own businesses but also enables their clients to be successful in their desire to dominate previous limitations. USAPL-friendly.',
    latitude: 38.8128844,
    longitude: -121.3036715,
  },
  {
    id: '34',
    name: 'Grand Slam USA',
    address: '2236 High St., Delano, CA 93215',
    equipment: [
      'calibrated plates',
      'dumbbells',
      '10+ Combo racks',
      '10+ benches',
      'various machines',
      'treadmill'
    ],
    hours: '24/7 for members',
    description: 'Together, through hard work, accountability, and relentless effort, we provide an environment that not only helps trainers start and grow their own businesses but also enables their clients to be successful in their desire to dominate previous limitations. USAPL-friendly.',
    latitude: 35.7878427,
    longitude: -119.2516124,
  },

  {
    id: '35',
    name: 'Tmwbarbell',
    address: '10832 Kyle St D, Los Alamitos, CA 90720',
    equipment: [
      'calibrated plates',
      'deadlift bar',
      'chalk',
      'kettle bells',
      'SSB bars',
      'trap bars',
      'power bars',
      'Rogue Wood jerk blocks',
      'benches',
      'Combo racks'
    ],
    hours: 'May vary',
    description: 'Community, Heavy Lifting, Progress',
    latitude: 33.8062202,
    longitude: -118.06485,
  },

  {
    id: '36',
    name: 'Wild Iron Gym',
    address: '950 Comstock St, Santa Clara, CA 95054',
    equipment: [
      'calibrated plates',
      'deadlift platforms',
      'cambered bar',
      'deadlift bars',
      'bumper plates',
      'swiss bar',
      'benches',
      'combo racks',
      'chains'
    ],
    hours: 'Mon: Closed, Tue: 5:30 PM - 8:00 PM, Wed: Closed, Thu: 5:30 PM - 8:00 PM, Fri: Closed, Sat: 8:30 AM - 12:00 PM, Sun: 8:30 AM - 12:00 PM',
    description: 'USPA-friendly',
    latitude: 37.3748096,
    longitude: -121.9510728,
  },

  {
    id: '37',
    name: 'Bladium Sports & Fitness Club',
    address: '800 W Tower Ave, Alameda, CA 94501',
    equipment: [
      'dumbbells',
      'cardio equipment',
      'soccer stadium',
      'pickle ball courts'
    ],
    hours: 'Sunday: 7 AM-6 PM, Monday: 5 AM-10 PM, Tuesday: 5 AM-10 PM, Wednesday: 5 AM-10 PM, Thursday: 5 AM-10 PM, Friday: 5 AM-8 PM, Saturday: 7 AM-6 PM',
    description: 'All your fitness and pickleball needs under one roof. Discover an enhanced fitness experience with The HUB, and explore our top-notch facilities, classes and programs.',
    latitude: 37.7817498,
    longitude: -122.3010747,
  },

  {
    id: '38',
    name: 'Speed Power Strength',
    address: '2140 Livingston St, Oakland, CA 94606',
    equipment: [
      'gymnastics rings',
      'power bars',
      'dumbbells',
      'squat racks',
      'trap bar',
      'bumper plates',
      'iron plates',
      'sled',
      'turf',
      'benches'
    ],
    hours: 'Mon: 7:00 AM - 10:00 AM, 5:00 PM - 8:00 PM, Tue: 5:00 PM - 8:00 PM, Wed: 5:00 PM - 8:00 PM, Thu: 7:00 AM - 10:00 AM, 5:00 PM - 8:00 PM, Fri: 5:00 PM - 8:00 PM, Sat: 10:00 AM - 1:00 PM, Sun: Closed',
    description: 'BEGINNER FRIENDLY, SMALL GROUP STRENGTH TRAINING + PERSONAL TRAINING FOR WORKING PROFESSIONALS.',
    latitude: 37.7815338,
    longitude: -122.2400174,
  },

  {
    id: '39',
    name: 'Beasts of the Bay Strength',
    address: '1041 Stuart St, Lafayette, CA 94549',
    equipment: [
      'rope climb',
      'iron plates',
      'power bar',
      'box jump',
      'dumbbells',
      'atlas stones',
      'squat racks'
    ],
    hours: 'May vary',
    description: 'Affiliated with USA weightlifting. Optimize performance, customize programming, take control of your nutrition.',
    latitude: 37.894683,
    longitude: -122.1093729,
  },

  {
    id: '40',
    name: 'Barbell Brigade',
    address: '646 Gibbons St, Los Angeles, CA 90031',
    equipment: [
      'bumper plates',
      'chalk stations',
      'dumbbells',
      'basketball court',
      'calibrated plates'
    ],
    hours: 'Sunday: 5 AM-12 AM, Monday: 5 AM-12 AM, Tuesday: 5 AM-12 AM, Wednesday: 5 AM-12 AM, Thursday: 5 AM-12 AM, Friday: 5 AM-12 AM, Saturday: 5 AM-12 AM',
    description: 'We\'re a 5,500 square foot facility with 16 squat racks, 11 benches, 6 deadlift platforms, and the most proven strength and bodybuilding equipment. Located in Downtown Los Angeles.',
    latitude: 34.066082,
    longitude: -118.2237428,
  },
  

  
];