export const gymData = [
  {
    id: '1',
    name: 'Underground Fitness',
    address: '2217 San Ramon Valley Blvd Suite E, San Ramon, CA',
    equipment: ['Squat Racks', 'Deadlift Platforms', 'Bench Press'],
    hours: 'Mon-Fri: 6am-10pm, Sat-Sun: 8am-8pm',
    description: 'A premier powerlifting gym with state-of-the-art equipment.',
    latitude: 37.7771,
    longitude: -121.9657,
  },
  {
    id: '2',
    name: '24 Hour Fitness',
    address: '4770 Willow Rd, Pleasanton, CA',
    equipment: ['Barbells', 'Squat Racks', 'Benches', 'Adjustable Benches', 'Dumbbells', 'Cardio Equipment'],
    hours: 'Mon-Sun: 24 hours',
    description: 'This is a test.',
    latitude: 37.6943,
    longitude: -121.9021,
  },
  {
    id: '3',
    name: '24 Hour Fitness',
    address: '4450 Norris Canyon Rd, San Ramon, CA',
    equipment: ['Barbells', 'Squat Racks', 'Benches', 'Adjustable Benches', 'Dumbbells', 'Cardio Equipment'],
    hours: 'Mon-Sun: 24 hours',
    description: 'San Ramon 24.',
    latitude: 37.7738,
    longitude: -121.9576,
  },
  {
    id: '4',
    name: 'California Strength',
    address: '1538, 2021 Omega Rd #120, San Ramon, CA',
    equipment: ['Bench Press', 'Deadlift Bars', 'Squat Racks'],
    hours: 'Mon-Sun: hours',
    description: 'this is california strength',
    latitude: 37.7875,
    longitude: -121.9639,
  },
  {
    id: '5',
    name: 'Reform Fitness',
    address: '1279 Quarry Ln, Pleasanton, CA',
    equipment: ['Barbells'],
    hours: 'Mon-Sun: hours',
    description: 'this is california strength',
    latitude: 37.675654,
    longitude: -121.9475664,
  },
  {
    id: '6',
    name: 'Bay Area Barbell',
    address: '2824 Regatta Blvd, Richmond, CA',
    equipment: [
      '6 Combo Racks (5 TSS & 1 ER)',
      '4 Deadlift Platforms',
      '2 Olympic Weightlifting Platforms',
      '2 Power Cages',
      '7,000+ lbs of Rogue Powerlifting Calibrated Plates',
      '2 full sets of Rogue Olympic Bumper Plates',
      '2 Eleiko Power Bars',
      'Kabuki Deadlift Bar',
      '10 Rogue Ohio Power Bars',
      '5 lbs - 120 lbs Dumbbells',
      'Leg Press Machine',
      'Lat Pull Down/ Low Row Machine'
    ],
    hours: 'Members: 5 AM - 11 PM last entry',
    description: 'The East Bay’s Premier Powerlifting Gym',
    latitude: 37.91486901701566,
    longitude: -122.34166100430903,
  },
  {
    id: '7',
    name: 'Backyard Barbell',
    address: '1630 Remuda Ln, San Jose, CA 95112',
    equipment: [
      'Competition Combo rack',
      'Power racks',
      'Kabuki Powerlifting plates',
      'Eleiko competition plates',
      'Strong man equipment: Yoke, Log, Farmer handles, Sled, Husafell stone, wheel barrow, Hungarian core blaster',
      'Texas Squat, Deadlift, and Power bars',
      'Safety squat bar, Duffalo bar, Swiss bar and every kind of specialty bar you can think of',
      'Belt squat Machine',
      'Elitefts Monster hack squat',
      'Reverse Hyper',
      'Dip bars',
      'Chest supported Row',
      'Bands, chains, and weight releasers',
      'Flat and adjustable benches',
      'Blocks for Block pulls and deficit deadlifts',
      'Deadlift platform with band attachments',
      'Dumbells 5-150lbs',
      '250lbs stack Lat pulldown with various attachments such as Fat Gripz, grenade handles, Different lat pulldown handles',
      'And much much more!'
    ],
    hours: 'Open 24 Hours, 365 days a year',
    description: '',
    latitude: 37.373003127731266,
    longitude: -121.9087751055745,
  },
  {
    id: '8',
    name: 'War Cat Fitness',
    address: '299 Bassett St, San Jose, CA',
    equipment: [
      '5 Texas Strength Systems Powerlifting Competition Racks (with updated Bench Pads)',
      'Rogue Powerlifting Competition Plates 1.25, 2.5, 5, 10, 15, 20, 25, 50kg Plates',
      'Cast Iron 2.5, 5, 10, 25 and 45lb Plates',
      '20kg Ohio Power Barbells',
      '45lb Ohio Power Barbells',
      '20kg Texas Strength Systems Barbell',
      '45lb Texas Deadlift Barbells',
      '45lb Rogue Deadlift Barbells',
      '45lb Kansas Power Barbells',
      '5 Deadlift Platforms',
      'Dumbbells 2.5-100lbs',
      'Kettlebells 10-175lbs',
      'Plate Loaded Dumbbells',
      '4 Elite Pro Adjustable Benches',
      '2 Rogue Flat Benches',
      '2 Rogue Westside Benches',
      '4 Power Rack Stations',
      'Landmine Row Station',
      'Rogue Iso Leg Press Machine',
      'Rogue Belt Squat Machine',
      'Rogue Reverse Hyper',
      'Rogue Lat Pulldown / Row Machine',
      'Double Column Cable Machine',
      'GHD Machine',
      '10’x10’ Stretching / Grappling Mat',
      '2 Assault AirBikes (for warming up)'
    ],
    hours: 'Monday - Friday: 5AM - 10PM, Saturday: 8 AM - 4 PM, Sunday: 8 AM - 2 PM',
    description: 'Best Strength Gym in The Bay Area',
    latitude: 37.339282520678154,
    longitude: -121.90042100254067,
  },
  {
    id: '9',
    name: '1RM Strength',
    address: '23412 Lyons Ave, Santa Clarita, CA',
    equipment: [
      'Texas Strength Systems Combo x2',
      'Ghost Combo Rack x2',
      'Rogue Combo Rack x1',
      'Deadlift Platforms x3',
      'Prime Fitness Leg Extension x1',
      'Prime Fitness Seated Row x1',
      'Prime Fitness Leg Press x1',
      'Prime Fitness Plate Loaded Incline Chest Press x1',
      'Atlantis Strength Lying Leg Curl',
      'Rogue Power Rack x1',
      'Rogue Squat Stand x1',
      'Rogue GHD x1',
      'Rogue Westside Reverse Hyper x1',
      'Rogue Belt Squat x1',
      'Rogue Adjustable Bench x2',
      'Flat Bench x2',
      '5-75lb Dumbbells x1',
      'Functional Trainer (Cables) x1',
      'Lat Pulldown/Low Row Machine x1',
      'Rogue Echo Bike x1',
      'Prime Fitness Attachments',
      'Hammer Strength Adductor/Abductor'
    ],
    hours: 'MWF: 3PM-9PM, TTh: 9AM-9PM, Sat:10AM-3PM, Sun:Closed',
    description: 'Premier Powerlifting & Powerlifting Gym',
    latitude: 34.378715123169584,
    longitude: -118.54307597502941,
  },
  {
    id: '10',
    name: 'Hidden Strength Gym',
    address: '1442 Arrow Hwy K, Irwindale, CA',
    equipment: [
      'Powerlifting',
      '5 Combo Racks',
      '3 Deadlift Platforms',
      'Calibrated Kilo Plates',
      '3 EliteFTS Comp. Benches',
      'Rogue Deadlift Bars & Ohio Power Bars',
      'Specialty bars (Safety Squat Bar, Duffalo Bar)',
      'Olympic lifting',
      'Olympic platform',
      'American Barbell Olympic Bar',
      'Bumper plates',
      'Strength/weight training',
      '6 Station Squat Rig',
      '8 Station Cable Tower',
      '5 - 125 LB Dumbbells',
      'Adjustable Benches (Incline, Decline, Flat)',
      'Leg Extension/Hamstring Curl Station',
      'Glute Hamstring Developer (GHD)',
      'Belt Squat',
      'Specialty Bars (EZ Bar, Trap Bar, Multi grip bar)',
      'Tricep Dip Stand',
      'Reverse Hyper',
      'Kettlebells, Medicine balls, Ply boxes, Battle Ropes'
    ],
    hours: '24/7',
    description: 'The #1 Private Gym in Irwindale. We have the equipment and environment that will help you reach your full potential. Open 24/7, 365 days.',
    latitude: 34.11342550674482,
    longitude: -117.97351237689239,
  },
  {
    id: '11',
    name: 'Exceed Performance',
    address: '2060 S Euclid St K, Anaheim, CA',
    equipment: [
      '1 Texas Strength System Combo Rack',
      '1 State of the Arc Combo Rack',
      '4 Custom',
      '1 Squat-only rack',
      '1 Power cages',
      '5 Deadlift Platforms',
      '2 Assault Bikes',
      '1 Treadmill',
      'Dumbbell sets 5-120lbs',
      'Dumbbell sets 5-50lbs',
      'Lat pulldown & mid row machine',
      'Leg press & hack squat machine',
      'Leg extension & leg curl plate loaded machine',
      'Glute Ham Developer',
      '2 Adjustable incline benches',
      'Functional Trainer Cable machine',
      '1 Flat Texas bench',
      '3000kg of powerlifting competition plates',
      '2000lbs of iron plates',
      '2000lbs of Uesaka & Neon Weightlifting Bumper Plates',
      '8 Power Bars',
      '2 Texas power bars',
      '4 deadlift bars',
      '2 DUFFALO BARS',
      '2 Safety Squat Bars',
      '3 squat bars',
      '1 OPEN trap bar',
      '1 swiss bar',
      '1 KABUKI POWER BAR',
      '1 KABUKI SQUAT BAR',
      '1 KABUKI DEADLIFT BAR',
      '3 men’s weightlifting bars',
      '2 women’s weightlifting bar',
      '2 Large Plyo Boxes',
      '2 Small Plyo Boxes',
      'Resistance bands from 10lbs-120lbs'
    ],
    hours: 'MONDAY-FRIDAY 10AM-7PM, 24 HOUR ACCESS FOR MEMBERS!',
    description: 'Powerlifting At It’s Finest In Anaheim, California!',
    latitude: 33.79646793232328,
    longitude: -117.9403268848602,
  },
  {
    id: '12',
    name: 'Old Skool Iron',
    address: '33 Commerce Pl, Vacaville, CA',
    equipment: [
      'six dead-lift platforms',
      'three ER Combo racks',
      'four power racks (full and half rack)',
      'deadlift bars',
      'squat bars',
      'smith machine',
      'competition Forza bench',
      'full rack of dumbbells up to 160 lbs. (going even heavier in the near future)',
      'adjustable moveable benches etc'
    ],
    hours: 'Mon - Fri 8:00am to 8:00pm Sat/Sun 8:00am to 4:00pm Open 365 days a year',
    description: 'A Serious Place To Lift and Train Hard',
    latitude: 38.35333697861697,
    longitude: -121.93548488158554,
  },
];